name: NET_DISSECT
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - tensorboard=2.19.0
  - numpy
  - matplotlib
  - pillow
  - pip=25.0
  - pip:
    - cmake
    - fastapi
    - groq
    - uvicorn
    - python-dotenv
